"""
replay.py — ERA5 sea-state replay mechanism (Modules 5.1 / 5.2A).

============================================================
PURPOSE
============================================================

Provides a deterministic, reproducible replay of real ERA5-derived
hourly sea-state sequences to drive the WEC RL environment.

The replay is the *outer* time grid (hourly, 1 ERA5 row per hour).
The WEC physics solver operates on its own *inner* time grid (0.1 s
per step).  These two grids are explicitly distinguished.

============================================================
DESIGN PRINCIPLES
============================================================

1. ERA5 hourly rows are the ground truth for sea state.
   They are NOT synthetic — they come from real reanalysis data.

2. The WEC physics (excitation force) is generated by Module 1's
   goa_seastate() conditioned on each ERA5 row.  Each 1-hour ERA5
   segment produces a synthetic surface realization.

3. Replay is *deterministic*: given the same DataFrame slice,
   start_index, and seed, the replay produces identical excitation
   force sequences and sea-state sequences.

4. The replay buffer distinguishes:
   - True sea-state (Hs_true, Tp_true, direction_true) — used by
     physics and leaked into info dict only.
   - Controller-visible observations — produced by Module 3 sensor.

============================================================
OUTER vs INNER TIME GRIDS
============================================================

OUTER GRID (sea-state / ERA5 / sensor):
    Resolution : 1 hour = 3600 s
    Step k     : corresponds to ERA5 record at index (start_idx + k)
    Duration   : n_hours ERA5 records

INNER GRID (WEC physics / Cummins):
    Resolution : DT_PHYSICS = 0.1 s
    Steps per hour : 3600 / 0.1 = 36 000

CONTROL GRID (RL actions):
    Resolution : DT_CONTROL = 1.0 s
    Steps per hour : 3600

The environment maps: 1 RL action → DT_CONTROL / DT_PHYSICS = 10
physics steps.

============================================================
WATER DEPTH
============================================================

The Goa deployment site depth is set at 30 m.  This matches the
approximate shelf depth at (15.5°N, 73.5°E).  It is a site-specific
constant factored into the EpisodeReplay config so it can be overridden
per-site.

Reference: Indian National Centre for Ocean Information Services (INCOIS)
bathymetry data for the Goa region.

============================================================
UNITS
============================================================
    Hs          : m
    Tp          : s
    direction   : degrees (ERA5 mwd convention, clockwise from North)
    u10, v10    : m/s
    time        : s (absolute, from start of episode)
    dt_physics  : s
    dt_control  : s
    depth_m     : m

============================================================
MODULE DEPENDENCIES (read-only)
============================================================
    module1_ocean.goa_seastate  — goa_seastate(), SeaStateResult
    module5_control.excitation  — build_wave_components(), WaveComponents
    module4_forecasting.era5_archive — load_era5_archive()  (optional)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional

import numpy as np
import pandas as pd

from module1_ocean.goa_seastate import goa_seastate, SeaStateResult
from module5_control.excitation import build_wave_components, WaveComponents

# ---------------------------------------------------------------------------
# Physical / numerical constants
# ---------------------------------------------------------------------------

#: Physics integrator timestep [s].
#: Must satisfy: dt_physics < pi / omega_max = pi / 1.4 ≈ 2.24 s.
#: Chosen at 0.1 s (T_n/75) for accuracy on the ~7.5 s natural period.
DT_PHYSICS: float = 0.1

#: RL control timestep [s].
#: One RL action is held for DT_CONTROL seconds before the next decision.
#: Chosen as 1.0 s ≈ T_n/7.5; small relative to wave period (Tp ~ 5–15 s)
#: but large enough to reduce unnecessary switching.
DT_CONTROL: float = 1.0

#: Number of physics steps per control step (must be integer).
N_PHYSICS_PER_CONTROL: int = int(round(DT_CONTROL / DT_PHYSICS))  # = 10

#: ERA5 outer grid step [s].
DT_ERA5: float = 3600.0

#: Number of physics steps per ERA5 hour.
N_PHYSICS_PER_HOUR: int = int(round(DT_ERA5 / DT_PHYSICS))  # = 36 000

#: Number of control steps per ERA5 hour.
N_CONTROL_PER_HOUR: int = int(round(DT_ERA5 / DT_CONTROL))  # = 3600

#: Default Goa deployment site water depth [m].
#: Shelf depth at ~15.5°N, 73.5°E.
DEPTH_GOA_M: float = 30.0

#: JONSWAP peakedness parameter (conventional default, not Goa-calibrated).
GAMMA_DEFAULT: float = 3.3


# ---------------------------------------------------------------------------
# EpisodeReplay dataclass
# ---------------------------------------------------------------------------

@dataclass
class EpisodeReplay:
    """
    All data needed to run one RL episode deterministically.

    The replay contains:
    - Hourly ERA5 sea-state records (outer grid, n_hours rows).
    - Pre-generated per-hour synthetic WEC excitation force sequences
      (inner grid).
    - Wind components for the GRU+wind forecaster.
    - Timestamps for the info dict.

    The environment reads excitation force values from this buffer at
    each physics step, advancing through the pre-generated sequences.

    Parameters
    ----------
    n_hours : int
        Number of ERA5 hours in the episode.
    Hs_true : np.ndarray, shape (n_hours,)
        True significant wave height per ERA5 hour [m].
    Tp_true : np.ndarray, shape (n_hours,)
        True peak wave period per ERA5 hour [s].
    direction_true : np.ndarray, shape (n_hours,)
        True mean wave direction per ERA5 hour [degrees].
    u10 : np.ndarray, shape (n_hours,)
        ERA5 10 m zonal wind [m/s].
    v10 : np.ndarray, shape (n_hours,)
        ERA5 10 m meridional wind [m/s].
    timestamps : list of pd.Timestamp
        UTC timestamps for each ERA5 hour.
    excitation_force : np.ndarray, shape (n_hours, N_PHYSICS_PER_HOUR)
        Pre-generated WEC heave excitation force [N] for each physics step
        in each ERA5 hour.  Built by goa_seastate() via Module 1.
    era5_start_index : int
        Index into the original ERA5 archive of the first record.
    seed : Optional[int]
        Random seed used to generate excitation forces.
    depth_m : float
        Water depth used for wave synthesis [m].
    wave_components_list : list of WaveComponents
        Per-hour WaveComponents objects (Module 5.2A).  Each stores the
        full spectral/phase data needed by IrregularExcitationModel.
        Empty list in legacy Module 5.1 replays (excitation_force buffer used).
        Non-empty when build_episode_replay() is called (Module 5.2A default).
    dt_physics : float
        Physics timestep [s].  Fixed at DT_PHYSICS.
    dt_control : float
        Control timestep [s].  Fixed at DT_CONTROL.
    """

    n_hours:              int
    Hs_true:              np.ndarray
    Tp_true:              np.ndarray
    direction_true:       np.ndarray
    u10:                  np.ndarray
    v10:                  np.ndarray
    timestamps:           List[pd.Timestamp]
    excitation_force:     np.ndarray          # shape (n_hours, N_PHYSICS_PER_HOUR)
    era5_start_index:     int
    seed:                 Optional[int]
    depth_m:              float
    wave_components_list: List[WaveComponents] = field(default_factory=list)
    dt_physics:           float = DT_PHYSICS
    dt_control:           float = DT_CONTROL

    # ------------------------------------------------------------------
    # Derived helpers
    # ------------------------------------------------------------------

    @property
    def n_control_steps(self) -> int:
        """Total number of RL control steps in the episode."""
        return self.n_hours * N_CONTROL_PER_HOUR

    @property
    def n_physics_steps(self) -> int:
        """Total number of physics steps in the episode."""
        return self.n_hours * N_PHYSICS_PER_HOUR

    @property
    def episode_duration_s(self) -> float:
        """Total episode duration [s]."""
        return float(self.n_hours) * DT_ERA5

    def get_excitation_at_physics_step(self, physics_step: int) -> float:
        """
        Return the excitation force [N] at a global physics step index.

        Parameters
        ----------
        physics_step : int
            Global index from 0 to n_physics_steps - 1.

        Returns
        -------
        float : F_exc [N]
        """
        hour_idx  = physics_step // N_PHYSICS_PER_HOUR
        step_idx  = physics_step %  N_PHYSICS_PER_HOUR
        hour_idx  = min(hour_idx, self.n_hours - 1)
        step_idx  = min(step_idx, N_PHYSICS_PER_HOUR - 1)
        return float(self.excitation_force[hour_idx, step_idx])

    def get_era5_hour_index(self, physics_step: int) -> int:
        """Return the ERA5 hour index corresponding to a physics step."""
        return min(physics_step // N_PHYSICS_PER_HOUR, self.n_hours - 1)

    def get_control_step_hour(self, control_step: int) -> int:
        """Return the ERA5 hour index corresponding to a control step."""
        return min(control_step // N_CONTROL_PER_HOUR, self.n_hours - 1)


# ---------------------------------------------------------------------------
# build_episode_replay — main factory
# ---------------------------------------------------------------------------

def build_episode_replay(
    df: pd.DataFrame,
    start_index: int,
    n_hours: int,
    seed: Optional[int] = None,
    depth_m: float = DEPTH_GOA_M,
    gamma: float = GAMMA_DEFAULT,
    dt_physics: float = DT_PHYSICS,
) -> EpisodeReplay:
    """
    Build a deterministic EpisodeReplay from an ERA5 DataFrame slice.

    Generates synthetic WEC excitation forces for each ERA5 hour using
    Module 1's goa_seastate().  Seeds are derived deterministically from
    the base seed so the full episode is reproducible.

    Parameters
    ----------
    df : pd.DataFrame
        ERA5 time series with columns: time, Hs_m, Tp_s, direction_deg,
        u10, v10.  Produced by load_era5_archive().
    start_index : int
        Index of the first ERA5 record to use (0-based row index in df).
    n_hours : int
        Number of ERA5 hours to include in the episode.
    seed : int or None
        Base random seed for reproducibility.  Hour i uses seed = seed + i.
        None = non-reproducible (seeds are None for all hours).
    depth_m : float
        Water depth [m].  Default is the Goa shelf depth (30 m).
    gamma : float
        JONSWAP peakedness parameter.  Default 3.3.
    dt_physics : float
        Physics timestep [s].  Default DT_PHYSICS = 0.1 s.

    Returns
    -------
    EpisodeReplay

    Raises
    ------
    ValueError
        If start_index + n_hours exceeds DataFrame length, required columns
        are missing, depth_m <= 0, or n_hours < 1.
    """
    # --- Validation ---
    required = {"time", "Hs_m", "Tp_s", "direction_deg", "u10", "v10"}
    missing  = required - set(df.columns)
    if missing:
        raise ValueError(f"DataFrame missing required columns: {sorted(missing)}")
    if n_hours < 1:
        raise ValueError(f"n_hours must be >= 1, got {n_hours}")
    if depth_m <= 0:
        raise ValueError(f"depth_m must be positive, got {depth_m}")
    if start_index < 0:
        raise ValueError(f"start_index must be >= 0, got {start_index}")
    end_index = start_index + n_hours
    if end_index > len(df):
        raise ValueError(
            f"start_index={start_index} + n_hours={n_hours} = {end_index} "
            f"exceeds DataFrame length {len(df)}."
        )

    # --- Slice the DataFrame ---
    slice_df = df.iloc[start_index:end_index].reset_index(drop=True)

    Hs_arr    = slice_df["Hs_m"].to_numpy(dtype=float)
    Tp_arr    = slice_df["Tp_s"].to_numpy(dtype=float)
    dir_arr   = slice_df["direction_deg"].to_numpy(dtype=float)
    u10_arr   = slice_df["u10"].to_numpy(dtype=float)
    v10_arr   = slice_df["v10"].to_numpy(dtype=float)
    timestamps = list(pd.to_datetime(slice_df["time"]))

    # --- Pre-generate per-hour wave components and excitation buffer ---
    # Module 5.2A: build_wave_components() replicates goa_seastate() internals
    # to expose (omega_j, Z_j) needed by IrregularExcitationModel.
    # The excitation_force buffer is retained for backward compatibility with
    # Module 5.1 tests; in 5.2A the environment uses wave_components_list instead.
    n_phys_per_hour    = int(round(DT_ERA5 / dt_physics))
    exc_buffer         = np.zeros((n_hours, n_phys_per_hour), dtype=float)
    wave_components_list: List[WaveComponents] = []

    for i in range(n_hours):
        Hs_i  = float(Hs_arr[i])
        Tp_i  = float(Tp_arr[i])
        dir_i = float(dir_arr[i])

        # Handle NaN rows by falling back to calm-sea defaults
        is_nan = np.isnan(Hs_i) or np.isnan(Tp_i) or np.isnan(dir_i)
        if is_nan:
            Hs_i, Tp_i, dir_i = 0.01, 8.0, 270.0

        # Clamp to safe physical range
        Hs_i = max(Hs_i, 0.01)
        Tp_i = max(Tp_i, 1.0)

        hour_seed = (seed + i) if seed is not None else None

        # Build WaveComponents (Module 5.2A) — exposes spectral components
        wc = build_wave_components(
            Hs=Hs_i,
            Tp=Tp_i,
            direction_deg=dir_i,
            gamma=gamma,
            seed=hour_seed,
        )
        wave_components_list.append(wc)

        # Also fill the legacy eta buffer (used by excitation_force field and
        # Module 5.1 tests; Module 5.2A environment uses IrregularExcitationModel)
        seastate: SeaStateResult = goa_seastate(
            Hs=Hs_i,
            Tp=Tp_i,
            direction_deg=dir_i,
            depth_m=depth_m,
            gamma=gamma,
            duration_s=DT_ERA5,
            dt=dt_physics,
            seed=hour_seed,
        )
        n_actual = len(seastate.eta)
        n_use    = min(n_actual, n_phys_per_hour)
        exc_buffer[i, :n_use] = seastate.eta[:n_use]
        if n_use < n_phys_per_hour:
            exc_buffer[i, n_use:] = exc_buffer[i, n_use - 1]

    return EpisodeReplay(
        n_hours=n_hours,
        Hs_true=Hs_arr,
        Tp_true=Tp_arr,
        direction_true=dir_arr,
        u10=u10_arr,
        v10=v10_arr,
        timestamps=timestamps,
        excitation_force=exc_buffer,
        era5_start_index=start_index,
        seed=seed,
        depth_m=depth_m,
        wave_components_list=wave_components_list,
        dt_physics=dt_physics,
        dt_control=DT_CONTROL,
    )


# ---------------------------------------------------------------------------
# Convenience: build a minimal synthetic replay for tests / smoke tests
# ---------------------------------------------------------------------------

def build_synthetic_replay(
    n_hours: int = 4,
    Hs: float = 1.5,
    Tp: float = 8.0,
    direction_deg: float = 270.0,
    u10: float = 5.0,
    v10: float = 2.0,
    seed: int = 0,
    depth_m: float = DEPTH_GOA_M,
    gamma: float = GAMMA_DEFAULT,
    dt_physics: float = DT_PHYSICS,
) -> EpisodeReplay:
    """
    Build a deterministic synthetic replay from constant sea-state parameters.

    Useful for unit tests and smoke tests that do not require real ERA5 data.

    Parameters
    ----------
    n_hours : int
        Number of hours to simulate.
    Hs, Tp, direction_deg : float
        Constant sea-state parameters for all hours.
    u10, v10 : float
        Constant wind components for all hours.
    seed : int
        Random seed.  Deterministic.
    depth_m, gamma, dt_physics : float
        Passed through to goa_seastate().

    Returns
    -------
    EpisodeReplay
    """
    start = pd.Timestamp("2020-01-01 00:00:00")
    timestamps = [start + pd.Timedelta(hours=i) for i in range(n_hours)]

    df = pd.DataFrame({
        "time":          timestamps,
        "Hs_m":          [Hs]           * n_hours,
        "Tp_s":          [Tp]           * n_hours,
        "direction_deg": [direction_deg] * n_hours,
        "u10":           [u10]          * n_hours,
        "v10":           [v10]          * n_hours,
    })

    return build_episode_replay(
        df=df,
        start_index=0,
        n_hours=n_hours,
        seed=seed,
        depth_m=depth_m,
        gamma=gamma,
        dt_physics=dt_physics,
    )
